---
name: build image

on:
  push:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build_docker_image:
    runs-on: ubuntu-latest
    container: quay.io/centos/centos:stream8
    steps:
      - uses: actions/checkout@v4
      - name: run build image
        run: |
          env
          bash build.sh
          yum -y install skopeo
          skopeo login docker.io -u jeffrey4l -p ${DOCKERP}
          skopeo copy tarball:image.tar docker://opstool/centos:stream8
        env:
          DOCKERU: ${{ secrets.DOCKERU }}
          DOCKERP: ${{ secrets.DOCKERP }}
