---
name: build image

on:
  - push
jobs:
  build_docker_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: run build image
        run: |
          sudo -E bash build.sh
