---
name: build image

on:
  - push
jobs:
  build_docker_image:
    runs-on: ubuntu-latest
    container: quay.io/centos/centos:stream8
    steps:
      - uses: actions/checkout@v4
      - name: run build image
        run: |
          bash build.sh
          yum -y install skopeo
          skopeo login docker.io -u {DOCKERU} -p ${DOCKERP}
          skopeo copy tarball:image.tar docker://jeffrey4l/centos:stream8
