---
name: build image

on:
  push:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build_docker_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install require package
        run: |
          apt update
          apt install -y qemu-user-binfmt buildah qemu-user-static wget dnf rpm
      - name: run build image
        run: |
          ARCH=x86_64 ./build.sh
          ARCH=aarch64 ./build.sh
        env:
          DOCKERU: ${{ secrets.DOCKERU }}
          DOCKERP: ${{ secrets.DOCKERP }}
