---
name: build image

on:
  push:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build_docker_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install require package
        run: |
          sudo apt update
          sudo apt install -y buildah qemu-user-static wget dnf rpm
      - name: run build image
        run: |
          ARCH=x86_64 sudo -E ./build.sh
          ARCH=aarch64 sudo -E ./build.sh
          ls -alh
        env:
          DOCKERU: ${{ secrets.DOCKERU }}
          DOCKERP: ${{ secrets.DOCKERP }}
